### PR TITLE
fix: Stop series data not saving when max values reached [PT-187949831]

### PR DESCRIPTION
**Pull request by dougmartin**
Previously there was a useCallback() wrapper on the stop time series function that depended on the formData but this caused issues with the formData being captured as an empty array at the start of multiple runs where the runs hit their max number of values.

This fix adds a ref to the formData so that the closure is not created.

### CODE REVIEW

**Comment by dougmartin** [comment]
This function:

```
stopTimeSeriesFnRef.current = sensor.collectTimeSeries(timeSeriesCapabilities.measurementPeriod, selectableSensorId, (values) => {
   ...
}
```

closed over the current value of `formData` in `onSensorStopTimeSeries` even though there is a `useCallback` that updates `onSensorStopTimeSeries` when `formData` changes.

I've tested this change and it works for both the manual stop button (which worked before) and the automatic stop (which was not working).

**Comment by pjanik** [comment]
Ah, I see it better now. However, I think we're fixing it on the wrong side, and there are definitely more issues in this code. If we add anything else (e.g., a new state) to the `onSensorStopTimeSeries`, the problem happens again, and it won't be fun to debug.

I think the last argument of `stopTimeSeriesFnRef` is essentially wrong and this part needs to be fixed. I think it should either:
1. Not reference any state, just refs, or use functional updates of state
2. Probably be wrapped in `useCallback` with dependencies

Currently, it references `formData` that is surely outdated, and the same with `rowIdx`. It might work just fine for data collection, and it might not sound that important, but I think this is an important concept in general. If not here, then in other places, and it's probably good to be on the same page (also, if I'm wrong here).

Probably both fixes should be combined, and it might look like this:

```javascript
    stopTimeSeriesFnRef.current = sensor.collectTimeSeries(timeSeriesCapabilities.measurementPeriod, selectableSensorId, useCallback((values) => {
        if (values.length <= MaxNumberOfTimeSeriesValues) {
          setFormData(prevData => {
            const newData = prevData.slice();
            newData[rowIdx] = {...newData[rowIdx], timeSeries: values, timeSeriesMetadata};
            return newData;
          });
        }
        if (values.length === MaxNumberOfTimeSeriesValues) {
          onSensorStopTimeSeries();
        }
      }, [rowIdx, onSensorStopTimeSeries, /* probably more things here */]);
      timeSeriesRecordingRowRef.current = rowIdx;
    };
```

And `onSensorStopTimeSeries` could use `useCallback` again.

**Comment by dougmartin** [comment]
@pjanik I tried your code and the callback passed to `collectTimeSeries` and invoked with each time series data collection still closes over the current `onSensorStopTimeSeries` function value and causes the bug to appear.  This project is out of money and the current fix works so I think we should go with it.

**Comment by pjanik** [comment]
Yeap, I haven't tested it, but I'd think that's the correct direction.

But sure, let's merge it as it is.

**Review by pjanik — APPROVED** [review]

**Pull request merged**
